# Tensors

In the first notebook ([vector.ipynb](https://github.com/ADGEfficiency/teaching-monolith/blob/master/numpy/1.vector.ipynb)) we dealt with vectors (one dimensional).  In the second notebook ([matrix.ipynb](https://github.com/ADGEfficiency/teaching-monolith/blob/master/numpy/2.matrix.ipynb)) we looked at arrays with two dimensions.

Now we deal with **Tensors** - arrays that can have many dimensions.

- n-dimensional arrays
- 3 = volume
- uppercase, bold $\textbf{A}_{i,j,k}$

## Working in three dimensions

Extension of two dimensions
- everything we saw in the previous notebook holds

Images
- height
- width
- channels (colors)

Sequential models
- (batch_size, num_timesteps, *features)

## Practical

Create an array filled from a normal distribution, with the shape
- 100 samples
- 64 timesteps
- 32 height
- 16 width
- 3 channels

## Practical

Aggregate by standard deviation `np.std` 
- over the width
- over the height
- over the channels
- over all data

## PNG to Numpy array

In [2]:
from PIL import Image

img = Image.open("data/abbyroad.png")
img.show()

To see how this picture looks like in RGB code, we apply the following function:

In [6]:
import numpy as np
array = np.array(img)
print(array.shape)
array

(2048, 2048, 3)


array([[[ 15,  13,  16],
        [ 15,  13,  16],
        [ 15,  13,  16],
        ...,
        [ 20,  20,  18],
        [ 17,  17,  15],
        [ 16,  16,  14]],

       [[ 16,  14,  17],
        [ 16,  14,  17],
        [ 16,  14,  17],
        ...,
        [ 21,  21,  19],
        [ 20,  20,  18],
        [ 20,  20,  18]],

       [[ 17,  15,  18],
        [ 17,  15,  18],
        [ 16,  14,  17],
        ...,
        [ 21,  21,  19],
        [ 21,  23,  20],
        [ 22,  24,  21]],

       ...,

       [[202, 194, 171],
        [199, 191, 168],
        [196, 188, 165],
        ...,
        [205, 195, 159],
        [209, 199, 163],
        [213, 203, 167]],

       [[201, 193, 170],
        [197, 189, 166],
        [195, 187, 164],
        ...,
        [206, 198, 161],
        [208, 200, 163],
        [213, 205, 168]],

       [[200, 192, 169],
        [196, 188, 165],
        [194, 186, 163],
        ...,
        [209, 201, 164],
        [210, 202, 165],
        [214, 206, 169]]

## Practical
Now create the negative version and grayscale version of that picture and save it in the data folder

In [28]:
# np.negative(array)
gray_img_array = np.mean(array, axis=2)
gray_img = np.mean(array, axis=2).shape
gray_img

(2048, 2048)

In [29]:
Image.fromarray(gray_img).show()

AttributeError: 'tuple' object has no attribute '__array_interface__'

In [33]:
kernel = np.array([
    [-1, -1, -1],
    [-1, 8, -1],
    [-1, -1, -1]
])

# exercise: slide the kernel through the black and white image

# create an empyt container in which the scalar products are going to be inserted

# loop over the image and apply the kernel to get the scaler product

# display the image

In [26]:
array

array([[[ 15,  13,  16],
        [ 15,  13,  16],
        [ 15,  13,  16],
        ...,
        [ 20,  20,  18],
        [ 17,  17,  15],
        [ 16,  16,  14]],

       [[ 16,  14,  17],
        [ 16,  14,  17],
        [ 16,  14,  17],
        ...,
        [ 21,  21,  19],
        [ 20,  20,  18],
        [ 20,  20,  18]],

       [[ 17,  15,  18],
        [ 17,  15,  18],
        [ 16,  14,  17],
        ...,
        [ 21,  21,  19],
        [ 21,  23,  20],
        [ 22,  24,  21]],

       ...,

       [[202, 194, 171],
        [199, 191, 168],
        [196, 188, 165],
        ...,
        [205, 195, 159],
        [209, 199, 163],
        [213, 203, 167]],

       [[201, 193, 170],
        [197, 189, 166],
        [195, 187, 164],
        ...,
        [206, 198, 161],
        [208, 200, 163],
        [213, 205, 168]],

       [[200, 192, 169],
        [196, 188, 165],
        [194, 186, 163],
        ...,
        [209, 201, 164],
        [210, 202, 165],
        [214, 206, 169]]

In [30]:
gray_img_array

array([[ 14.66666667,  14.66666667,  14.66666667, ...,  19.33333333,
         16.33333333,  15.33333333],
       [ 15.66666667,  15.66666667,  15.66666667, ...,  20.33333333,
         19.33333333,  19.33333333],
       [ 16.66666667,  16.66666667,  15.66666667, ...,  20.33333333,
         21.33333333,  22.33333333],
       ...,
       [189.        , 186.        , 183.        , ..., 186.33333333,
        190.33333333, 194.33333333],
       [188.        , 184.        , 182.        , ..., 188.33333333,
        190.33333333, 195.33333333],
       [187.        , 183.        , 181.        , ..., 191.33333333,
        192.33333333, 196.33333333]])

In [35]:
kernel = np.array([
    [-1, -1, -1],
    [-1, 8, -1],
    [-1, -1, -1]
])

In [44]:
# exercise: slide the kernel through the black and white image
kernel_size = len(kernel)
image_size = len(gray_img)

new_size = image_size - (kernel_size-1)
container = np.empty((new_size, new_size))


In [47]:
last_element = image_size - kernel_size

for i in range(last_element):
    i_end = i + 3
    for j in range(last_element):
        j_end = j + 3
        snippet = gray_img[i:i_end, j:j_end]
        container[i, j] = np.multiply(kernel, snippet)

In [48]:
new_image = Image.fromarray(container)
new_image.show()

ValueError: tile cannot extend outside image

In [ ]:
# create an empyt container in which the scalar products are going to be inserted

In [ ]:
# loop over the image and apply the kernel to get the scaler product


In [34]:
# display the image


## Answers
You are encourage to give it a try before you look at the solution

## Practical - convolution

Implement the convolution operation - we will do this together as a class! The idea looks like this 
<img src="assets/conv.png" alt="" width="300"/>